import CategoryIcon from './category.svg?react'
import ArrowRightIcon from './arrow-right.svg?react'
import BoxIcon from './box.svg?react'
import DiscountIcon from './discount.svg?react'
import InfoCircleIcon from './info-circle.svg?react'
import LightIcon from './light.svg?react'
import LogoutIcon from './logout.svg?react'
import MoonIcon from './moon.svg?react'
import Profile2UserIcon from './profile-2user.svg?react'
import Setting2Icon from './setting-2.svg?react'
import TrendUpIcon from './trend-up.svg?react'
import FileDownload from './file-download.svg?react'
import BoxTickICon from './box-tick.svg?react'
import ShoppingCartIcon from './shopping-cart.svg?react'
import CoinIcon from './coin.svg?react'
import RotateIcon from './3d-rotate.svg?react'
import TrendingUpIcon from './trending-up.svg?react'
import TrendingDownIcon from './trending-down.svg?react'
import MenuIcon from './menu.svg?react'
import NotificationIcon from './notification.svg?react'
import CalenderIcon from './calender.svg?react'
import ArrowDownIcon from './Arrow Down.svg?react'
import ProfileIcon from './Profile.svg?react'
import SearchIcon from "./search.svg?react";
import CloseIcon from "./close.svg?react";

export { MenuIcon, TrendingUpIcon,TrendingDownIcon, BoxTickICon,ShoppingCartIcon, CoinIcon, RotateIcon, CategoryIcon, ArrowRightIcon, BoxIcon, DiscountIcon, InfoCircleIcon, LightIcon, LogoutIcon, MoonIcon, Profile2UserIcon, Setting2Icon, TrendUpIcon, FileDownload, NotificationIcon, CalenderIcon, ArrowDownIcon, ProfileIcon, SearchIcon, CloseIcon }